modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/wolfieboy09/Mekanism-x-Northstar/issues"
[[mods]]
modId="mek_x_star"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/wolfieboy09/Mekanism-x-Northstar/refs/heads/master/updates.json"
displayURL="https://github.com/wolfieboy09/Mekanism-x-Northstar"
logoFile="mek_x_star_logo.png"
credits=""
authors="${mod_authors}"

description='''${mod_description}'''
[[dependencies.mek_x_star]]
    modId="forge"
    mandatory=true #mandatory
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.mek_x_star]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.mek_x_star]]
    modId="mekanism"
    mandatory=true
    versionRange="[1.20.1-10.4.8.43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mek_x_star]]
    modId="northstar"
    mandatory=true
    versionRange="[0.1cb-1.20.1,)"
    ordering="NONE"
    side="BOTH"